---
title: "NLP - Data Exploration"
author: "Claus Bo Hansen"
date: "November 15, 2019"
output:
  html_document:
    theme: sandstone
    fig_width: 14
    fig_height: 8
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: true
    number_sections: true
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, comment = NA)

# Make sure that environment is empty
rm(list=ls())

# Load configuration
source("Config.R")

# Load libraries
library(tm)

# Load data
load(paste(outputDir, "01-GetData.RData", sep = ""))

# Dataset to explore
contentSources <- c("blogs", "news", "twitter")


```


This document is part of the capstone project in the Data Science Specialization on Johns Hopkins.




```{r blogs news twitter, results = 'asis'}

for (contentSource in contentSources) {
  
  cat(paste("\n# ", contentSource, "\n", sep = ""))
  dataset <- eval(as.name(contentSource))
  
  cat(paste("Number of strings in set: ", format(length(dataset), big.mark = ","), "\n", sep = ""))
  
}

# Test
test <- "This is a test, where I will test what is in the test document"

termFreq(test, control = list(wordLengths = c(2, Inf)))


```



